class AddIndexes < ActiveRecord::Migration
  def self.up
    add_index :approvals, :user_id, :name => 'user_id_ix'
    add_index :approvals, [:approvable_id, :approvable_type], :name => 'approvable_ix'
    add_index :assignments, :user_id, :name => 'user_id_ix'
    add_index :assignments, :role_id, :name => 'role_id_ix'
    add_index :bam_to_fam_features, :bam_to_fam_map_id, :name => 'bam_to_fam_map_id_ix'
    add_index :bam_to_fam_features, :feature_id, :name => 'feature_id_ix'
    add_index :bam_to_fam_features, :step_id, :name => 'step_id_ix'
    add_index :bam_to_fam_maps, :step_id, :name => 'step_id_ix'
    add_index :build_features, [:buildable_id, :buildable_type], :name => 'buildable_ix'
    add_index :business_areas, :iteration_id, :name => 'iteration_id_ix'
    add_index :business_areas, :parent_id, :name => 'parent_id_ix'
    add_index :business_processes, :iteration_id, :name => 'iteration_id_ix'
    add_index :business_process_elements, :business_process_id, :name => 'business_process_id_ix'
    add_index :fam_to_tam_maps, :feature_id, :name => 'feature_id_ix'
    add_index :fam_to_tam_maps, :build_feature_id, :name => 'build_feature_id_ix'
    add_index :features, :functional_work_unit_id, :name => 'functional_work_unit_id_ix'
    add_index :flows, :business_process_element_id, :name => 'business_process_element_id_ix'
    add_index :flows, :target_element_id, :name => 'target_element_id_ix'
    add_index :functional_work_units, :business_area_id, :name => 'business_area_id_ix'
    add_index :interfaces, :lba_id, :name => 'lba_id_ix'
    add_index :issues, [:issueable_id, :issueable_type], :name => 'issueable_ix'
    add_index :lbas, :parent_id, :name => 'parent_id_ix'
    add_index :lbas, :iteration_id, :name => 'iteration_id_ix'
    add_index :lbos, :business_area_id, :name => 'business_area_id_ix'
    add_index :logical_entities, :lbo_id, :name => 'lbo_id_ix'
    add_index :logical_entity_attributes, :logical_entity_id, :name => 'logical_entity_id_ix'
    add_index :paths, :business_process_id, :name => 'business_process_id_ix'
    add_index :paths, :iteration_id, :name => 'iteration_id_ix'
    add_index :steps, :path_id, :name => 'path_id_ix'
    add_index :steps, :business_process_element_id, :name => 'business_process_element_id_ix'    
    add_index :steps, :iteration_id, :name => 'iteration_id_ix'
    add_index :watchings, :user_id, :name => 'user_id_ix'
    add_index :watchings, [:watchable_id, :watchable_type], :name => 'watchable_ix'
  end

  def self.down
    remove_index :approvals, :name => 'user_id_ix'
    remove_index :approvals, :name => 'approvable_ix'
    remove_index :assignments, :name => 'user_id_ix'
    remove_index :assignments, :name => 'role_id_ix'
    remove_index :bam_to_fam_features, :name => 'bam_to_fam_map_id_ix'
    remove_index :bam_to_fam_features, :name => 'feature_id_ix'
    remove_index :bam_to_fam_features, :name => 'step_id_ix'
    remove_index :bam_to_fam_maps, :name => 'step_id_ix'
    remove_index :build_features, :name => 'buildable_ix'
    remove_index :business_areas, :name => 'iteration_id_ix'
    remove_index :business_areas, :name => 'parent_id_ix'
    remove_index :business_processes, :name => 'iteration_id_ix'
    remove_index :business_process_elements, :name => 'business_process_id_ix'
    remove_index :fam_to_tam_maps, :name => 'feature_id_ix'
    remove_index :fam_to_tam_maps, :name => 'build_feature_id_ix'
    remove_index :features, :name => 'functional_work_unit_id_ix'
    remove_index :flows, :name => 'business_process_element_id_ix'
    remove_index :flows, :name => 'target_element_id_ix'
    remove_index :functional_work_units, :name => 'business_area_id_ix'
    remove_index :interfaces, :name => 'lba_id_ix'
    remove_index :issues, :name => 'issueable_ix'
    remove_index :lbas, :name => 'parent_id_ix'
    remove_index :lbas, :name => 'iteration_id_ix'
    remove_index :lbos, :name => 'business_area_id_ix'
    remove_index :logical_entities, :name => 'lbo_id_ix'
    remove_index :logical_entity_attributes, :name => 'logical_entity_id_ix'
    remove_index :paths, :name => 'business_process_id_ix'
    remove_index :paths, :name => 'iteration_id_ix'
    remove_index :steps, :name => 'path_id_ix'
    remove_index :steps, :name => 'business_process_element_id_ix'    
    remove_index :steps, :name => 'iteration_id_ix'
    remove_index :watchings, :name => 'user_id_ix'
    remove_index :watchings, :name => 'watchable_ix'
  end
end
